---
abstract: 'The great new HTML::Cleaner!'
author:
  - 'Daniel de Oliveira Mantovani <daniel.oliveira.mantovani@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Cleaner
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Entities: 0
  Test::More: 0
version: 0.05
